build:
    root_path: './'
    environment:
        python:
            version: 3.9.9
            virtualenv: true
    dependencies:
        before:
            -
                command: curl https://sh.rustup.rs -sSf | sh <input.txt>

